# Generated by Django 3.1.4 on 2021-01-06 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFaultReport',
            fields=[
                ('Enq_No', models.AutoField(primary_key=True, serialize=False, verbose_name='Enq #')),
                ('Subject_Title', models.TextField(blank=True, verbose_name='Subject Title')),
                ('description', models.TextField(blank=True, verbose_name='Full Problem or Request Description')),
                ('date_created', models.DateField(blank=True, verbose_name='Date Resolution Expected (mandatory)')),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
